export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const REGISTER_OBSERVER_WAITING = 'REGISTER_OBSERVER_WAITING';
export const REGISTER_OBSERVER_SUCCESS = 'REGISTER_OBSERVER_SUCCESS';
export const REGISTER_OBSERVER_REDIRECTED = 'REGISTER_OBSERVER_REDIRECTED';
export const REGISTER_OBSERVER_FAIL = 'REGISTER_OBSERVER_FAIL';

export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_REDIRECTED = 'CONTACT_REDIRECTED';
export const CONTACT_FAIL = 'CONTACT_FAIL';